### ISSUE TITLE
Command injection - mkdir/rm

### ISSUE THREAD

**Issue by AAA97AAA** [dorlafo/CS412-project#11]
In the following file, we can see that the user input is parsed but invalid characters are not escaped. Thus, we are able to open a calculator on the server side:

https://github.com/dorlafo/CS412-project/blob/0fa2767f92d323e8abd56e6cb0ea904282f8374f/src/server.c#L273-L280

Here's the input I gave to your client program:
```
login Acidburn
pass CrashOverride 
mkdir lol&&/bin/gnome-calculator
```

**Comment by dorlafo** [comment]
Duplicate of #1
