### ISSUE TITLE
grep command injection

### ISSUE THREAD

**Issue by PizzaWhisperer** [dorlafo/CS412-project#14]
After running `make`, launch the server with `./bin/server`.

Then launch the client with `./bin/client 127.0.0.1 1337` and feed it with 
```
login Acidburn
pass CrashOverride
grep stuff;xcalc
```
which pops a calc on the server side.
Indeed at this line https://github.com/dorlafo/CS412-project/blob/0fa2767f92d323e8abd56e6cb0ea904282f8374f/src/server.c#L278 the user input is not escaped.

**Comment by dorlafo** [comment]
Duplicate of #9
